In [1]:
import pandas as pd
import numpy as np
from dimod import BinaryQuadraticModel
from dwave.system import LeapHybridSampler

import warnings
warnings.filterwarnings('ignore')


import logging
import os
import time

from datetime import datetime
from collections import Counter
from itertools import combinations, combinations_with_replacement, permutations

In [2]:
df = pd.read_csv('footy.csv')

In [3]:
df = df[['Opponent', 'xGA', 'xG', 'Poss', 'Result']]

In [4]:
df['Team'] = 'Arsenal'

df.loc[df.Result == 'W', 'Result'] = 1
df.loc[df.Result == 'L', 'Result'] = -1
df.loc[df.Result == 'D', 'Result'] = 0

In [5]:
#df['tot'] = df.groupby('Opponent')['Result'].transform(sum)

In [6]:
#df = df.drop_duplicates('Opponent')

In [7]:
df.loc[df.Result == -1, 'ResultB'] = 1
df.loc[df.Result == 1, 'ResultB'] = -1
df.loc[df.Result == 0, 'ResultB'] = 0

In [13]:
df

           Opponent  xGA   xG  Poss Result     Team  ResultB
0            Fulham  0.2  1.8    55      1  Arsenal     -1.0
1          West Ham  1.9  1.4    62      1  Arsenal     -1.0
2         Liverpool  3.2  1.2    33     -1  Arsenal      1.0
3     Sheffield Utd  0.2  0.4    63      1  Arsenal     -1.0
4   Manchester City  1.5  0.9    41     -1  Arsenal      1.0
5    Leicester City  1.2  0.9    57     -1  Arsenal      1.0
6    Manchester Utd  0.3  1.1    47      1  Arsenal     -1.0
7       Aston Villa  1.7  1.5    58     -1  Arsenal      1.0
8      Leeds United  2.5  0.9    35      0  Arsenal      0.0
9            Wolves  1.4  1.2    56     -1  Arsenal      1.0
10        Tottenham  0.5  0.8    68     -1  Arsenal      1.0
11          Burnley  0.9  1.5    65     -1  Arsenal      1.0
12      Southampton  1.1  0.7    36      0  Arsenal      0.0
13          Everton  0.8  1.4    57     -1  Arsenal      1.0
14          Chelsea  2.3  2.1    41      1  Arsenal     -1.0
15         Brighton  0.8  1.2    50      1  Arsenal     -1.0
16        West Brom  0.4  3.3    61      1  Arsenal     -1.0
17   Crystal Palace  0.9  0.6    67      0  Arsenal      0.0
18    Newcastle Utd  0.2  2.8    66      1  Arsenal     -1.0
19      Southampton  1.2  2.0    43      1  Arsenal     -1.0
20   Manchester Utd  1.5  1.1    43      0  Arsenal      0.0
21           Wolves  1.5  0.6    45     -1  Arsenal      1.0
22      Aston Villa  1.1  1.1    65     -1  Arsenal      1.0
23     Leeds United  0.7  2.4    47      1  Arsenal     -1.0
24  Manchester City  2.0  0.3    44     -1  Arsenal      1.0